version: "3"
networks:
    app-network: null
services:
    nginx:
        image: "nginx:stable-alpine"
        container_name: "nginx_movie_pro"
        ports:
            - "80:80"
        volumes:
            - "./:/var/www/html"
            - "./nginx-default.conf:/etc/nginx/conf.d/default.conf"
        depends_on:
            - php
            - mysql
        networks:
            - app-network
    mysql:
        image: "mariadb:10.5.8"
        container_name: "mysql_movie_pro"
        restart: unless-stopped
        tty: true
        command: --max_allowed_packet=1073741824
        ports:
            - "3307:3306"
        environment:
            MYSQL_DATABASE: movie_pro
            MYSQL_USER: movie_pro
            MYSQL_PASSWORD: 123456@
            MYSQL_ROOT_PASSWORD: secret
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - app-network
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: "php_movie_pro"

        volumes:
            - "./:/var/www/html"
            - "./php.ini:/usr/local/etc/php/php.ini"
        ports:
            - "9000:9000"
        networks:
            - app-network

    npm:
        image: "node:13.7"
        container_name: "npm_movie_pro"
        volumes:
            - "./:/var/www/html"
        working_dir: /var/www/html
        entrypoint:
            - npm
